# Ridge Regression Artwork Pricer

Regularized log-linear Ridge regression baseline for artwork valuation.

This notebook uses `../../Data/sampled_sets`:
- train: `Artwork_2026_finetune_40000_2023_2024_train_sample10000.csv`
- test: 2025 quarterly CSV files sampled to `TEST_ROWS_PER_QUARTER` rows each

The notebook trains two comparable Ridge models:
- `Ridge Regression - No Estimates`: uses artwork, artist, date, size, medium, material, auction house, location, and market features.
- `Ridge Regression - With Log Estimates`: uses the same features plus cleaned/log-scaled auction-house estimate inputs.

Both models train on `log1p(ah_price_usd)` and back-transform predictions with `expm1`.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

from ridge_pricer.features import (
    load_artwork_data,
    split_train_test,
    make_model_frame,
    fit_feature_schema,
    apply_feature_schema,
    print_feature_summary,
)
from ridge_pricer.modeling import (
    DEFAULT_ALPHAS,
    fit_ridge_log_price_model,
    predict_price_from_log_model,
    evaluate_price_predictions,
    evaluate_by_quarter,
    evaluate_by_price_bucket,
    get_top_coefficients,
    ridge_training_history,
)

DATA_DIR = Path("../../Data/sampled_sets_100k")
TARGET_COL = "ah_price_usd"
TRAIN_ROWS = 40_000
TEST_ROWS_PER_QUARTER = 1000
SPLIT_RANDOM_STATE = 42
SPLIT_KEY_COL = "lot_url"
CAP_OVERSIZED_REQUESTS = True
MIN_CATEGORY_COUNT = 20
VERBOSE_PREPROCESSING = True
VERBOSE_MODEL = True
ALPHAS = DEFAULT_ALPHAS
RIDGE_VALIDATION_FRACTION = 0.10  # set 0 to use RidgeCV without alpha-by-alpha diagnostics
RIDGE_LOG_PERIOD = 1
RIDGE_EVAL_METRIC = "log_RMSE"

MODEL_NO_ESTIMATES = "Ridge Regression - No Estimates"
MODEL_WITH_ESTIMATES = "Ridge Regression - With Log Estimates"

## 1. Load Sampled Data

In [2]:
raw_df = load_artwork_data(DATA_DIR, verbose=VERBOSE_PREPROCESSING)
print(raw_df.shape)
raw_df[["source_file", "source_quarter", "sale_date", "ah_price_usd", "lot_url"]].head()

[ridge features] Loading artwork files from /srv/notebooks/[6.0] ML Pricers/Data/sampled_sets_100k
[ridge features]   loaded Artwork_2026_finetune_100000_2022_2024_train_all_eligible.csv: 38,261 rows, 70 columns
[ridge features]   loaded Artwork_2026_finetune_100000_q2025Q1_sample1000.csv: 1,000 rows, 70 columns
[ridge features]   loaded Artwork_2026_finetune_100000_q2025Q2_sample1000.csv: 1,000 rows, 70 columns
[ridge features]   loaded Artwork_2026_finetune_100000_q2025Q3_sample1000.csv: 1,000 rows, 70 columns
[ridge features]   loaded Artwork_2026_finetune_100000_q2025Q4_sample1000.csv: 1,000 rows, 70 columns
[ridge features] Loaded combined dataframe: 42,261 rows, 70 columns
(42261, 70)

,source_file,source_quarter,sale_date,ah_price_usd,lot_url
0,Artwork_2026_finetune_100000_2022_2024_train_a...,None,2022-07-01,31771.00,https://www.christies.com/en/lot/lot-6380380?l...
1,Artwork_2026_finetune_100000_2022_2024_train_a...,None,2024-11-20,63000.00,https://www.christies.com/en/lot/lot-6508480?l...
2,Artwork_2026_finetune_100000_2022_2024_train_a...,None,2023-11-23,746.65,https://www.sothebys.com/en/buy/auction/2023/m...
3,Artwork_2026_finetune_100000_2022_2024_train_a...,None,2022-09-23,11299.27,https://www.sothebys.com/en/buy/auction/2022/m...
4,Artwork_2026_finetune_100000_2022_2024_train_a...,None,2024-11-07,1852.50,https://hindmanauctions.com/auctions/2084-19th...

## 2. Train/Test Split

Uses `SPLIT_KEY_COL = "lot_url"` for duplicate/leakage checks. The train row count and per-quarter test row count are notebook variables. If `CAP_OVERSIZED_REQUESTS = True`, oversized requests are capped to the maximum rows available after filtering.

In [3]:
train_raw, test_raw = split_train_test(
    raw_df,
    train_rows=TRAIN_ROWS,
    test_rows_per_quarter=TEST_ROWS_PER_QUARTER,
    dedupe_key_col=SPLIT_KEY_COL,
    cap_oversized_requests=CAP_OVERSIZED_REQUESTS,
    random_state=SPLIT_RANDOM_STATE,
    verbose=VERBOSE_PREPROCESSING,
)
print("train raw:", train_raw.shape)
print("test raw:", test_raw.shape)
print("test quarters:")
print(test_raw["source_quarter"].value_counts().sort_index())
print("train/test lot_url overlap:", len(set(train_raw["lot_url"].dropna()) & set(test_raw["lot_url"].dropna())))

[ridge features] Initial split: train=38,261, explicit test=4,000
[ridge features] Requested 40,000 train rows, only 38,261 available; using all available train rows.
[ridge features] Using train rows: 38,261
[ridge features] Train contains 4,001 duplicate lot_url rows; keeping them to preserve exact train size.
[ridge features] De-duplicated test lot_url: 4,000->4,000
[ridge features] Removed train/test overlapping lot_url values from test: 4,000->4,000
[ridge features] Requested test rows per quarter: 1,000
[ridge features] Actual test rows per quarter: {'2025Q1': 1000, '2025Q2': 1000, '2025Q3': 1000, '2025Q4': 1000}
[ridge features] Final split: train=38,261, test=4,000
train raw: (38261, 70)
test raw: (4000, 70)
test quarters:
source_quarter
2025Q1    1000
2025Q2    1000
2025Q3    1000
2025Q4    1000
Name: count, dtype: int64
train/test lot_url overlap: 0

## 3. Feature Engineering: No Estimates

This is the baseline Ridge feature set. It follows the agreed forced inputs, with `sale_date` and `year_of_creation` moved to numeric features. Auction estimate fields are retained for reporting but excluded from model training.

In [4]:
train_frame, feature_cols, categorical_cols, numeric_cols = make_model_frame(
    train_raw,
    target_col=TARGET_COL,
    include_estimates=False,
    verbose=VERBOSE_PREPROCESSING,
)
test_frame, _, _, _ = make_model_frame(
    test_raw,
    target_col=TARGET_COL,
    include_estimates=False,
    verbose=VERBOSE_PREPROCESSING,
)

schema = fit_feature_schema(
    train_frame,
    feature_cols,
    categorical_cols,
    min_category_count=MIN_CATEGORY_COUNT,
    verbose=VERBOSE_PREPROCESSING,
)

X_train = apply_feature_schema(train_frame, feature_cols, categorical_cols, schema, verbose=VERBOSE_PREPROCESSING)
X_test = apply_feature_schema(test_frame, feature_cols, categorical_cols, schema, verbose=VERBOSE_PREPROCESSING)
y_train_log = train_frame["log_target_price_usd"]

print("X_train no estimates:", X_train.shape)
print("X_test no estimates:", X_test.shape)
feature_report = print_feature_summary(
    train_frame,
    feature_cols,
    categorical_cols,
    numeric_cols,
    schema=schema,
)
feature_report

[ridge features] Building Ridge model frame from 38,261 rows using target_col='ah_price_usd', include_estimates=False
[ridge features] Filtered invalid/non-positive targets: 38,261->38,261
[ridge features] Engineered 24 features (10 categorical, 14 numeric).
[ridge features]   auction estimate fields retained for reporting but excluded from model features
[ridge features] Building Ridge model frame from 4,000 rows using target_col='ah_price_usd', include_estimates=False
[ridge features] Filtered invalid/non-positive targets: 4,000->4,000
[ridge features] Engineered 24 features (10 categorical, 14 numeric).
[ridge features]   auction estimate fields retained for reporting but excluded from model features
[ridge features] Fitting Ridge feature schema with min_category_count=20
[ridge features]   categorical auction_house: 7 kept levels from 5 observed
[ridge features]   categorical location: 13 kept levels from 12 observed
[ridge features]   categorical material_clean: 137 kept levels from 10,658 observed
[ridge features]   categorical artwork_title_clean: 20 kept levels from 29,326 observed
[ridge features]   categorical medium: 12 kept levels from 12 observed
[ridge features]   categorical signed: 4 kept levels from 2 observed
[ridge features]   categorical titled: 4 kept levels from 2 observed
[ridge features]   categorical dated: 4 kept levels from 2 observed
[ridge features]   categorical artist_name_grouped: 284 kept levels from 9,983 observed
[ridge features]   categorical edition_clean: 2 kept levels from 1 observed
[ridge features]   numeric medians stored for 14 features
[ridge features] Applying Ridge feature schema to 38,261 rows and 24 features
[ridge features] Applying Ridge feature schema to 4,000 rows and 24 features
X_train no estimates: (38261, 24)
X_test no estimates: (4000, 24)
Training rows: 38,261
Training features: 24
Categorical features (10): ['auction_house', 'location', 'material_clean', 'artwork_title_clean', 'medium', 'signed', 'titled', 'dated', 'artist_name_grouped', 'edition_clean']
Numeric features (14): ['sale_date_ordinal', 'sale_year_num', 'sale_month_num', 'year_of_creation_num', 'length_cm', 'height_cm', 'width_cm', 'GSPC', 'FTSE', 'IXIC', 'DJI', 'VIX', 'BZ_F', 'FVX']

,feature,role,transformation,missing_rate,unique_count_before_grouping,train_schema_levels,example_values
0,auction_house,categorical,Cleaned categorical from raw auction_house; ra...,0.000000,5,7.0,"Christies, Sotheby's, Hindman"
1,location,categorical,Cleaned categorical from raw location; rare le...,0.000000,12,13.0,"London, New York, Hong Kong"
2,material_clean,categorical,Lexically cleaned raw material text; rare clea...,0.000000,10658,137.0,"coloured pencil graphite paper, cast stone, wa..."
3,artwork_title_clean,categorical,Cleaned categorical from artwork_title; rare t...,0.000000,29326,20.0,"""Stamped Indelibly"" mouth, Liseur dans un faut..."
4,medium,categorical,Cleaned categorical from raw medium; rare leve...,0.000000,12,12.0,"drawing, sculpture, painting"
5,signed,categorical,Cleaned categorical yes/no value from signed.,0.000000,2,4.0,"yes, no"
6,titled,categorical,Cleaned categorical yes/no value from titled.,0.000000,2,4.0,"yes, no"
7,dated,categorical,Cleaned categorical yes/no value from dated.,0.000000,2,4.0,"yes, no"
8,artist_name_grouped,categorical,Cleaned categorical from artist_name; rare art...,0.000000,9983,284.0,"Tom Wesselmann, Jacques Lipchitz, Dong Kingman"
9,edition_clean,categorical,Cleaned categorical from edition; rare levels ...,0.000000,1,2.0,__missing__
10,sale_date_ordinal,numeric,Numeric ordinal day derived from sale_date.,0.000000,370,NaN,"738337, 739210, 738847"
11,sale_year_num,numeric,Numeric sale year derived from sale_date.,0.000000,3,NaN,"2022.0, 2024.0, 2023.0"
12,sale_month_num,numeric,Numeric sale month derived from sale_date.,0.000000,12,NaN,"7.0, 11.0, 11.0"
13,year_of_creation_num,numeric,Numeric conversion of year_of_creation.,0.291184,395,NaN,"1968.0, 1930.0, 1970.0"
14,length_cm,numeric,Numeric length converted to centimeters using ...,0.786859,1381,NaN,"55.2, 36.83, 53.34"
15,height_cm,numeric,Numeric height converted to centimeters using ...,0.128094,2662,NaN,"13.8, 38.0, 25.5"
16,width_cm,numeric,Numeric width converted to centimeters using u...,0.249497,2465,NaN,"19.2, 57.0, 25.5"
17,GSPC,numeric,Numeric market index level.,0.000000,36,NaN,"4130.29, 6032.38, 4567.8"
18,FTSE,numeric,Numeric market index level.,0.000000,36,NaN,"109.5683, 123.711, 112.8533"
19,IXIC,numeric,Numeric market index level.,0.000000,36,NaN,"12390.69, 19218.17, 14226.22"
20,DJI,numeric,Numeric market index level.,0.000000,36,NaN,"32845.13, 44910.65, 35950.89"
21,VIX,numeric,Numeric market/risk index level.,0.000000,35,NaN,"21.33, 13.51, 12.92"
22,BZ_F,numeric,Numeric Brent crude proxy.,0.000000,36,NaN,"111.51, 74.16, 81.72"
23,FVX,numeric,Numeric 5-year treasury yield proxy.,0.000000,35,NaN,"2.7, 4.05, 4.31"

## 4. Feature Engineering: With Estimates

This version uses the same rows and base features, then adds cleaned/log-scaled auction estimate inputs:
- `log_auction_low_estimate_usd`
- `log_auction_high_estimate_usd`
- `log_auction_estimate_midpoint_usd`
- `auction_estimate_range_ratio`

Raw estimate USD values are retained for reporting/export, but they are not used as Ridge training features. Zero or negative estimates are treated as missing before log transformation.

In [5]:
train_frame_est, feature_cols_est, categorical_cols_est, numeric_cols_est = make_model_frame(
    train_raw,
    target_col=TARGET_COL,
    include_estimates=True,
    verbose=VERBOSE_PREPROCESSING,
)
test_frame_est, _, _, _ = make_model_frame(
    test_raw,
    target_col=TARGET_COL,
    include_estimates=True,
    verbose=VERBOSE_PREPROCESSING,
)

schema_est = fit_feature_schema(
    train_frame_est,
    feature_cols_est,
    categorical_cols_est,
    min_category_count=MIN_CATEGORY_COUNT,
    verbose=VERBOSE_PREPROCESSING,
)

X_train_est = apply_feature_schema(train_frame_est, feature_cols_est, categorical_cols_est, schema_est, verbose=VERBOSE_PREPROCESSING)
X_test_est = apply_feature_schema(test_frame_est, feature_cols_est, categorical_cols_est, schema_est, verbose=VERBOSE_PREPROCESSING)

print("X_train with estimates:", X_train_est.shape)
print("X_test with estimates:", X_test_est.shape)
feature_report_est = print_feature_summary(
    train_frame_est,
    feature_cols_est,
    categorical_cols_est,
    numeric_cols_est,
    schema=schema_est,
)
feature_report_est

[ridge features] Building Ridge model frame from 38,261 rows using target_col='ah_price_usd', include_estimates=True
[ridge features] Filtered invalid/non-positive targets: 38,261->38,261
[ridge features] Engineered 28 features (10 categorical, 18 numeric).
[ridge features]   included auction estimate numeric features: ['log_auction_low_estimate_usd', 'log_auction_high_estimate_usd', 'log_auction_estimate_midpoint_usd', 'auction_estimate_range_ratio']
[ridge features] Building Ridge model frame from 4,000 rows using target_col='ah_price_usd', include_estimates=True
[ridge features] Filtered invalid/non-positive targets: 4,000->4,000
[ridge features] Engineered 28 features (10 categorical, 18 numeric).
[ridge features]   included auction estimate numeric features: ['log_auction_low_estimate_usd', 'log_auction_high_estimate_usd', 'log_auction_estimate_midpoint_usd', 'auction_estimate_range_ratio']
[ridge features] Fitting Ridge feature schema with min_category_count=20
[ridge features]   categorical auction_house: 7 kept levels from 5 observed
[ridge features]   categorical location: 13 kept levels from 12 observed
[ridge features]   categorical material_clean: 137 kept levels from 10,658 observed
[ridge features]   categorical artwork_title_clean: 20 kept levels from 29,326 observed
[ridge features]   categorical medium: 12 kept levels from 12 observed
[ridge features]   categorical signed: 4 kept levels from 2 observed
[ridge features]   categorical titled: 4 kept levels from 2 observed
[ridge features]   categorical dated: 4 kept levels from 2 observed
[ridge features]   categorical artist_name_grouped: 284 kept levels from 9,983 observed
[ridge features]   categorical edition_clean: 2 kept levels from 1 observed
[ridge features]   numeric medians stored for 18 features
[ridge features] Applying Ridge feature schema to 38,261 rows and 28 features
[ridge features] Applying Ridge feature schema to 4,000 rows and 28 features
X_train with estimates: (38261, 28)
X_test with estimates: (4000, 28)
Training rows: 38,261
Training features: 28
Categorical features (10): ['auction_house', 'location', 'material_clean', 'artwork_title_clean', 'medium', 'signed', 'titled', 'dated', 'artist_name_grouped', 'edition_clean']
Numeric features (18): ['sale_date_ordinal', 'sale_year_num', 'sale_month_num', 'year_of_creation_num', 'length_cm', 'height_cm', 'width_cm', 'GSPC', 'FTSE', 'IXIC', 'DJI', 'VIX', 'BZ_F', 'FVX', 'log_auction_low_estimate_usd', 'log_auction_high_estimate_usd', 'log_auction_estimate_midpoint_usd', 'auction_estimate_range_ratio']

,feature,role,transformation,missing_rate,unique_count_before_grouping,train_schema_levels,example_values
0,auction_house,categorical,Cleaned categorical from raw auction_house; ra...,0.000000,5,7.0,"Christies, Sotheby's, Hindman"
1,location,categorical,Cleaned categorical from raw location; rare le...,0.000000,12,13.0,"London, New York, Hong Kong"
2,material_clean,categorical,Lexically cleaned raw material text; rare clea...,0.000000,10658,137.0,"coloured pencil graphite paper, cast stone, wa..."
3,artwork_title_clean,categorical,Cleaned categorical from artwork_title; rare t...,0.000000,29326,20.0,"""Stamped Indelibly"" mouth, Liseur dans un faut..."
4,medium,categorical,Cleaned categorical from raw medium; rare leve...,0.000000,12,12.0,"drawing, sculpture, painting"
5,signed,categorical,Cleaned categorical yes/no value from signed.,0.000000,2,4.0,"yes, no"
6,titled,categorical,Cleaned categorical yes/no value from titled.,0.000000,2,4.0,"yes, no"
7,dated,categorical,Cleaned categorical yes/no value from dated.,0.000000,2,4.0,"yes, no"
8,artist_name_grouped,categorical,Cleaned categorical from artist_name; rare art...,0.000000,9983,284.0,"Tom Wesselmann, Jacques Lipchitz, Dong Kingman"
9,edition_clean,categorical,Cleaned categorical from edition; rare levels ...,0.000000,1,2.0,__missing__
10,sale_date_ordinal,numeric,Numeric ordinal day derived from sale_date.,0.000000,370,NaN,"738337, 739210, 738847"
11,sale_year_num,numeric,Numeric sale year derived from sale_date.,0.000000,3,NaN,"2022.0, 2024.0, 2023.0"
12,sale_month_num,numeric,Numeric sale month derived from sale_date.,0.000000,12,NaN,"7.0, 11.0, 11.0"
13,year_of_creation_num,numeric,Numeric conversion of year_of_creation.,0.291184,395,NaN,"1968.0, 1930.0, 1970.0"
14,length_cm,numeric,Numeric length converted to centimeters using ...,0.786859,1381,NaN,"55.2, 36.83, 53.34"
15,height_cm,numeric,Numeric height converted to centimeters using ...,0.128094,2662,NaN,"13.8, 38.0, 25.5"
16,width_cm,numeric,Numeric width converted to centimeters using u...,0.249497,2465,NaN,"19.2, 57.0, 25.5"
17,GSPC,numeric,Numeric market index level.,0.000000,36,NaN,"4130.29, 6032.38, 4567.8"
18,FTSE,numeric,Numeric market index level.,0.000000,36,NaN,"109.5683, 123.711, 112.8533"
19,IXIC,numeric,Numeric market index level.,0.000000,36,NaN,"12390.69, 19218.17, 14226.22"
20,DJI,numeric,Numeric market index level.,0.000000,36,NaN,"32845.13, 44910.65, 35950.89"
21,VIX,numeric,Numeric market/risk index level.,0.000000,35,NaN,"21.33, 13.51, 12.92"
22,BZ_F,numeric,Numeric Brent crude proxy.,0.000000,36,NaN,"111.51, 74.16, 81.72"
23,FVX,numeric,Numeric 5-year treasury yield proxy.,0.000000,35,NaN,"2.7, 4.05, 4.31"
24,log_auction_low_estimate_usd,numeric,log1p(cleaned auction-house low estimate USD);...,0.000157,5297,NaN,"9.8067, 11.0021, 7.8503"
25,log_auction_high_estimate_usd,numeric,log1p(cleaned auction-house high estimate USD)...,0.000157,5590,NaN,"10.0944, 11.2898, 8.5432"
26,log_auction_estimate_midpoint_usd,numeric,log1p(cleaned auction estimate midpoint USD); ...,0.000157,6188,NaN,"9.9609, 11.1563, 8.2556"
27,auction_estimate_range_ratio,numeric,Cleaned estimate spread divided by cleaned mid...,0.000157,3533,NaN,"0.2857, 0.2857, 0.6667"

## 5. Train Ridge Models With Alpha Diagnostics

In [6]:
ridge_model = fit_ridge_log_price_model(
    X_train,
    y_train_log,
    categorical_cols=categorical_cols,
    numeric_cols=numeric_cols,
    alphas=ALPHAS,
    validation_fraction=RIDGE_VALIDATION_FRACTION,
    log_period=RIDGE_LOG_PERIOD,
    eval_metric=RIDGE_EVAL_METRIC,
    random_state=SPLIT_RANDOM_STATE,
    verbose=VERBOSE_MODEL,
)
test_pred = predict_price_from_log_model(ridge_model, X_test)

ridge_model_est = fit_ridge_log_price_model(
    X_train_est,
    y_train_log,
    categorical_cols=categorical_cols_est,
    numeric_cols=numeric_cols_est,
    alphas=ALPHAS,
    validation_fraction=RIDGE_VALIDATION_FRACTION,
    log_period=RIDGE_LOG_PERIOD,
    eval_metric=RIDGE_EVAL_METRIC,
    random_state=SPLIT_RANDOM_STATE,
    verbose=VERBOSE_MODEL,
)
test_pred_est = predict_price_from_log_model(ridge_model_est, X_test_est)

print("Selected alpha no estimates:", ridge_model.selected_alpha_)
print("Selected alpha with estimates:", ridge_model_est.selected_alpha_)

training_history = ridge_training_history(ridge_model)
training_history.insert(0, "model", MODEL_NO_ESTIMATES)

training_history_est = ridge_training_history(ridge_model_est)
training_history_est.insert(0, "model", MODEL_WITH_ESTIMATES)

training_history_comparison = pd.concat([training_history, training_history_est], ignore_index=True)
training_history_comparison

[ridge model] Training Ridge on 38,261 rows and 24 features
[ridge model] Alpha grid: [0.001, 0.0029286445646252374, 0.008576958985908946, 0.025118864315095794, 0.07356422544596414, 0.21544346900318845, 0.630957344480193, 1.8478497974222907, 5.411695265464638, 15.848931924611142, 46.41588833612782, 135.93563908785268, 398.1071705534969, 1165.9144011798312, 3414.5488738336007, 10000.0]
[ridge model] Running alpha diagnostics: train_fit=34,434, validation=3,827, eval_metric=log_RMSE, log_period=1
[ridge model] [01/16] alpha=0.001 log_RMSE=1.49088 log_MAE=1.14543 RMSE=1536919.95 MAE=211310.62
[ridge model] [02/16] alpha=0.00292864 log_RMSE=1.49089 log_MAE=1.14540 RMSE=1536983.92 MAE=211321.46
[ridge model] [03/16] alpha=0.00857696 log_RMSE=1.49087 log_MAE=1.14545 RMSE=1537016.94 MAE=211342.15
[ridge model] [04/16] alpha=0.0251189 log_RMSE=1.49086 log_MAE=1.14545 RMSE=1537100.91 MAE=211350.18
[ridge model] [05/16] alpha=0.0735642 log_RMSE=1.49086 log_MAE=1.14543 RMSE=1537307.93 MAE=211348.38
[ridge model] [06/16] alpha=0.215443 log_RMSE=1.49081 log_MAE=1.14545 RMSE=1538110.69 MAE=211448.25
[ridge model] [07/16] alpha=0.630957 log_RMSE=1.49083 log_MAE=1.14557 RMSE=1540308.03 MAE=211729.19
[ridge model] [08/16] alpha=1.84785 log_RMSE=1.49096 log_MAE=1.14590 RMSE=1546118.24 MAE=212424.97
[ridge model] [09/16] alpha=5.4117 log_RMSE=1.49311 log_MAE=1.14817 RMSE=1560397.18 MAE=214142.68
[ridge model] [10/16] alpha=15.8489 log_RMSE=1.50382 log_MAE=1.15909 RMSE=1585349.43 MAE=217827.49
[ridge model] [11/16] alpha=46.4159 log_RMSE=1.53136 log_MAE=1.18375 RMSE=1611022.95 MAE=223326.99
[ridge model] [12/16] alpha=135.936 log_RMSE=1.56985 log_MAE=1.21540 RMSE=1628416.16 MAE=228168.07
[ridge model] [13/16] alpha=398.107 log_RMSE=1.60580 log_MAE=1.24439 RMSE=1638779.26 MAE=231589.45
[ridge model] [14/16] alpha=1165.91 log_RMSE=1.64008 log_MAE=1.27280 RMSE=1647080.74 MAE=234509.51
[ridge model] [15/16] alpha=3414.55 log_RMSE=1.69272 log_MAE=1.31562 RMSE=1656282.33 MAE=237709.90
[ridge model] [16/16] alpha=10000 log_RMSE=1.78726 log_MAE=1.39366 RMSE=1664623.23 MAE=241059.21
[ridge model] Selected alpha from validation diagnostics: 0.21544346900318845
[ridge model] Training Ridge on 38,261 rows and 28 features
[ridge model] Alpha grid: [0.001, 0.0029286445646252374, 0.008576958985908946, 0.025118864315095794, 0.07356422544596414, 0.21544346900318845, 0.630957344480193, 1.8478497974222907, 5.411695265464638, 15.848931924611142, 46.41588833612782, 135.93563908785268, 398.1071705534969, 1165.9144011798312, 3414.5488738336007, 10000.0]
[ridge model] Running alpha diagnostics: train_fit=34,434, validation=3,827, eval_metric=log_RMSE, log_period=1
[ridge model] [01/16] alpha=0.001 log_RMSE=0.63886 log_MAE=0.45484 RMSE=1056013.65 MAE=84066.85
[ridge model] [02/16] alpha=0.00292864 log_RMSE=0.63899 log_MAE=0.45496 RMSE=1055926.02 MAE=83978.66
[ridge model] [03/16] alpha=0.00857696 log_RMSE=0.63893 log_MAE=0.45491 RMSE=1055887.09 MAE=83983.30
[ridge model] [04/16] alpha=0.0251189 log_RMSE=0.63892 log_MAE=0.45490 RMSE=1055853.28 MAE=83967.12
[ridge model] [05/16] alpha=0.0735642 log_RMSE=0.63891 log_MAE=0.45490 RMSE=1055849.86 MAE=83973.54
[ridge model] [06/16] alpha=0.215443 log_RMSE=0.63893 log_MAE=0.45490 RMSE=1055753.25 MAE=83917.55
[ridge model] [07/16] alpha=0.630957 log_RMSE=0.63878 log_MAE=0.45477 RMSE=1055562.82 MAE=83891.39
[ridge model] [08/16] alpha=1.84785 log_RMSE=0.63860 log_MAE=0.45448 RMSE=1054257.98 MAE=83450.45
[ridge model] [09/16] alpha=5.4117 log_RMSE=0.63834 log_MAE=0.45423 RMSE=1053243.00 MAE=83188.21
[ridge model] [10/16] alpha=15.8489 log_RMSE=0.63880 log_MAE=0.45461 RMSE=1050973.21 MAE=82862.45
[ridge model] [11/16] alpha=46.4159 log_RMSE=0.64105 log_MAE=0.45678 RMSE=1049534.00 MAE=83339.32
[ridge model] [12/16] alpha=135.936 log_RMSE=0.64455 log_MAE=0.45982 RMSE=1048263.54 MAE=84003.10
[ridge model] [13/16] alpha=398.107 log_RMSE=0.64785 log_MAE=0.46225 RMSE=1045885.55 MAE=83279.32
[ridge model] [14/16] alpha=1165.91 log_RMSE=0.65080 log_MAE=0.46377 RMSE=1039294.50 MAE=79733.30
[ridge model] [15/16] alpha=3414.55 log_RMSE=0.65602 log_MAE=0.46619 RMSE=1040323.59 MAE=76744.96
[ridge model] [16/16] alpha=10000 log_RMSE=0.67946 log_MAE=0.48800 RMSE=1137114.62 MAE=100140.69
[ridge model] Selected alpha from validation diagnostics: 5.411695265464638
Selected alpha no estimates: 0.21544346900318845
Selected alpha with estimates: 5.411695265464638

,model,iteration,alpha,log_MAE,log_RMSE,log_R2,MAE,RMSE,MAPE,R2
0,Ridge Regression - No Estimates,1,0.001000,1.145430,1.490882,0.518014,211310.621610,1.536920e+06,2.996128,0.139667
1,Ridge Regression - No Estimates,2,0.002929,1.145401,1.490888,0.518010,211321.464273,1.536984e+06,2.996117,0.139595
2,Ridge Regression - No Estimates,3,0.008577,1.145450,1.490866,0.518025,211342.151981,1.537017e+06,2.996242,0.139558
3,Ridge Regression - No Estimates,4,0.025119,1.145452,1.490862,0.518027,211350.183322,1.537101e+06,2.996223,0.139464
4,Ridge Regression - No Estimates,5,0.073564,1.145432,1.490856,0.518031,211348.379316,1.537308e+06,2.995978,0.139232
5,Ridge Regression - No Estimates,6,0.215443,1.145454,1.490806,0.518064,211448.248555,1.538111e+06,2.995915,0.138333
6,Ridge Regression - No Estimates,7,0.630957,1.145566,1.490829,0.518048,211729.187322,1.540308e+06,2.995436,0.135869
7,Ridge Regression - No Estimates,8,1.847850,1.145900,1.490964,0.517961,212424.970582,1.546118e+06,2.995794,0.129338
8,Ridge Regression - No Estimates,9,5.411695,1.148167,1.493110,0.516573,214142.679403,1.560397e+06,3.002235,0.113182
9,Ridge Regression - No Estimates,10,15.848932,1.159093,1.503821,0.509612,217827.493074,1.585349e+06,3.037535,0.084593
10,Ridge Regression - No Estimates,11,46.415888,1.183752,1.531365,0.491484,223326.985306,1.611023e+06,3.134907,0.054704
11,Ridge Regression - No Estimates,12,135.935639,1.215402,1.569847,0.465605,228168.066940,1.628416e+06,3.290714,0.034182
12,Ridge Regression - No Estimates,13,398.107171,1.244390,1.605795,0.440850,231589.450510,1.638779e+06,3.446780,0.021851
13,Ridge Regression - No Estimates,14,1165.914401,1.272797,1.640085,0.416716,234509.506353,1.647081e+06,3.566402,0.011916
14,Ridge Regression - No Estimates,15,3414.548874,1.315622,1.692718,0.378678,237709.901692,1.656282e+06,3.692820,0.000845
15,Ridge Regression - No Estimates,16,10000.000000,1.393657,1.787259,0.307336,241059.214084,1.664623e+06,3.871749,-0.009244
16,Ridge Regression - With Log Estimates,1,0.001000,0.454845,0.638860,0.911497,84066.847196,1.056014e+06,0.532032,0.593834
17,Ridge Regression - With Log Estimates,2,0.002929,0.454960,0.638986,0.911462,83978.663964,1.055926e+06,0.532251,0.593902
18,Ridge Regression - With Log Estimates,3,0.008577,0.454912,0.638926,0.911478,83983.295785,1.055887e+06,0.532156,0.593932
19,Ridge Regression - With Log Estimates,4,0.025119,0.454899,0.638921,0.911480,83967.116712,1.055853e+06,0.532153,0.593958
20,Ridge Regression - With Log Estimates,5,0.073564,0.454896,0.638912,0.911482,83973.536960,1.055850e+06,0.532146,0.593960
21,Ridge Regression - With Log Estimates,6,0.215443,0.454896,0.638927,0.911478,83917.550089,1.055753e+06,0.532209,0.594034
22,Ridge Regression - With Log Estimates,7,0.630957,0.454772,0.638781,0.911519,83891.385039,1.055563e+06,0.532024,0.594181
23,Ridge Regression - With Log Estimates,8,1.847850,0.454479,0.638598,0.911569,83450.447737,1.054258e+06,0.531806,0.595184
24,Ridge Regression - With Log Estimates,9,5.411695,0.454232,0.638345,0.911639,83188.205886,1.053243e+06,0.531686,0.595963
25,Ridge Regression - With Log Estimates,10,15.848932,0.454605,0.638795,0.911515,82862.453192,1.050973e+06,0.532558,0.597702
26,Ridge Regression - With Log Estimates,11,46.415888,0.456775,0.641053,0.910888,83339.319312,1.049534e+06,0.535683,0.598803
27,Ridge Regression - With Log Estimates,12,135.935639,0.459822,0.644554,0.909912,84003.100026,1.048264e+06,0.540053,0.599774
28,Ridge Regression - With Log Estimates,13,398.107171,0.462247,0.647854,0.908987,83279.320360,1.045886e+06,0.544644,0.601588
29,Ridge Regression - With Log Estimates,14,1165.914401,0.463773,0.650804,0.908157,79733.295037,1.039294e+06,0.550874,0.606593
30,Ridge Regression - With Log Estimates,15,3414.548874,0.466189,0.656018,0.906679,76744.958352,1.040324e+06,0.564724,0.605814
31,Ridge Regression - With Log Estimates,16,10000.000000,0.488004,0.679457,0.899891,100140.692973,1.137115e+06,0.618416,0.529052

## 6. Overall Comparison Metrics

Only the approved metrics are reported: `MAE`, `RMSE`, `MAPE`, and `R2`.

In [7]:
overall_metrics = pd.DataFrame([
    evaluate_price_predictions(test_frame["target_price_usd"], test_pred, label=MODEL_NO_ESTIMATES),
    evaluate_price_predictions(test_frame_est["target_price_usd"], test_pred_est, label=MODEL_WITH_ESTIMATES),
])
overall_metrics

,model,n,MAE,RMSE,MAPE,R2
0,Ridge Regression - No Estimates,4000,116385.254497,767508.275594,3.067082,-0.172310
1,Ridge Regression - With Log Estimates,4000,38654.834341,225154.969957,0.762924,0.899112

## 7. Quarterly Comparison Metrics

In [8]:
quarter_metrics = pd.concat(
    [
        evaluate_by_quarter(test_frame, test_pred, label=MODEL_NO_ESTIMATES),
        evaluate_by_quarter(test_frame_est, test_pred_est, label=MODEL_WITH_ESTIMATES),
    ],
    ignore_index=True,
).sort_values(["quarter", "model"]).reset_index(drop=True)
quarter_metrics

,model,n,MAE,RMSE,MAPE,R2,quarter
0,Ridge Regression - No Estimates,1000,66497.752206,3.792236e+05,2.579188,0.152989,2025Q1
1,Ridge Regression - With Log Estimates,1000,28944.342731,1.805496e+05,0.779289,0.808004,2025Q1
2,Ridge Regression - No Estimates,1000,195835.365147,1.168088e+06,2.124852,-0.372962,2025Q2
3,Ridge Regression - With Log Estimates,1000,48357.572981,2.032525e+05,0.839344,0.958430,2025Q2
4,Ridge Regression - No Estimates,1000,38690.533265,2.309539e+05,5.006013,-0.643464,2025Q3
5,Ridge Regression - With Log Estimates,1000,13465.741131,6.128250e+04,0.834175,0.884287,2025Q3
6,Ridge Regression - No Estimates,1000,164517.367368,8.914575e+05,2.558273,0.002506,2025Q4
7,Ridge Regression - With Log Estimates,1000,63851.680522,3.537143e+05,0.598889,0.842959,2025Q4

## 8. Metrics By Price Range

In [9]:
price_bucket_metrics = pd.concat(
    [
        evaluate_by_price_bucket(test_frame, test_pred, label=MODEL_NO_ESTIMATES),
        evaluate_by_price_bucket(test_frame_est, test_pred_est, label=MODEL_WITH_ESTIMATES),
    ],
    ignore_index=True,
).sort_values(["price_bucket", "model"]).reset_index(drop=True)
price_bucket_metrics

,model,n,MAE,RMSE,MAPE,R2,price_bucket
0,Ridge Regression - No Estimates,302,2.306323e+05,1.145141e+06,0.910023,-116.048957,$100k-$500k
1,Ridge Regression - With Log Estimates,302,8.075869e+04,1.071207e+05,0.382613,-0.024227,$100k-$500k
2,Ridge Regression - No Estimates,1256,8.098542e+03,4.254179e+04,3.713324,-1446.578290,$1k-$5k
3,Ridge Regression - With Log Estimates,1256,2.034229e+03,8.466597e+03,0.841233,-56.336120,$1k-$5k
4,Ridge Regression - No Estimates,633,4.631752e+04,2.035392e+05,0.979467,-101.515020,$25k-$100k
5,Ridge Regression - With Log Estimates,633,1.877991e+04,2.536197e+04,0.391709,-0.591686,$25k-$100k
6,Ridge Regression - No Estimates,163,2.071106e+06,3.441755e+06,0.852813,-0.603727,$500k+
7,Ridge Regression - With Log Estimates,163,6.614840e+05,1.103680e+06,0.329832,0.835086,$500k+
8,Ridge Regression - No Estimates,1252,1.327156e+04,2.445762e+04,1.234990,-19.881385,$5k-$25k
9,Ridge Regression - With Log Estimates,1252,6.066425e+03,1.448980e+04,0.543898,-6.329190,$5k-$25k
10,Ridge Regression - No Estimates,394,5.566014e+03,1.997719e+04,12.752149,-6402.389693,<$1k
11,Ridge Regression - With Log Estimates,394,9.403177e+02,2.057658e+03,2.276354,-66.934094,<$1k

## 9. Coefficient Inspection

Ridge is interpretable after preprocessing. Coefficients are on the log-price scale.

In [10]:
top_coefficients = get_top_coefficients(ridge_model, top_n=40)
top_coefficients.insert(0, "model", MODEL_NO_ESTIMATES)

top_coefficients_est = get_top_coefficients(ridge_model_est, top_n=40)
top_coefficients_est.insert(0, "model", MODEL_WITH_ESTIMATES)

coefficient_comparison = pd.concat([top_coefficients, top_coefficients_est], ignore_index=True)
coefficient_comparison

,model,feature,coefficient,abs_coefficient
0,Ridge Regression - No Estimates,categorical__artist_name_grouped_Claude Monet,3.614077,3.614077
1,Ridge Regression - No Estimates,categorical__artist_name_grouped_Frederick Conway,-3.541657,3.541657
2,Ridge Regression - No Estimates,categorical__artist_name_grouped_Jean-michel B...,3.344927,3.344927
3,Ridge Regression - No Estimates,categorical__artist_name_grouped_Jean-Michel B...,3.267181,3.267181
4,Ridge Regression - No Estimates,categorical__artist_name_grouped_Artist Unknown,-3.197591,3.197591
...,...,...,...,...
75,Ridge Regression - With Log Estimates,categorical__artist_name_grouped_Mark Grotjahn,-0.277301,0.277301
76,Ridge Regression - With Log Estimates,categorical__artist_name_grouped_Zhang Xiaogang,-0.275713,0.275713
77,Ridge Regression - With Log Estimates,categorical__artist_name_grouped_Caroline Walker,0.275213,0.275213
78,Ridge Regression - With Log Estimates,categorical__artist_name_grouped_After Pablo P...,0.275211,0.275211
79,Ridge Regression - With Log Estimates,categorical__material_clean_lithograph wove paper,0.273754,0.273754

## 10. Export Results

In [11]:
output_dir = Path("outputs")
output_dir.mkdir(exist_ok=True)

scored_test = test_frame[[
    "ID",
    "lot_url",
    "source_quarter",
    "sale_date",
    "target_price_usd",
    "auction_low_estimate_usd",
    "auction_high_estimate_usd",
    "auction_estimate_midpoint_usd",
    "auction_estimate_range_usd",
    "log_auction_low_estimate_usd",
    "log_auction_high_estimate_usd",
    "log_auction_estimate_midpoint_usd",
    "auction_estimate_range_ratio",
]].copy()
scored_test["ridge_pred_no_estimates_usd"] = test_pred
scored_test["ridge_error_no_estimates_usd"] = scored_test["ridge_pred_no_estimates_usd"] - scored_test["target_price_usd"]
scored_test["ridge_pred_with_estimates_usd"] = test_pred_est
scored_test["ridge_error_with_estimates_usd"] = scored_test["ridge_pred_with_estimates_usd"] - scored_test["target_price_usd"]

scored_test.to_csv(output_dir / "ridge_test_predictions.csv", index=False)
overall_metrics.to_csv(output_dir / "ridge_overall_metrics.csv", index=False)
quarter_metrics.to_csv(output_dir / "ridge_quarter_metrics.csv", index=False)
price_bucket_metrics.to_csv(output_dir / "ridge_price_bucket_metrics.csv", index=False)
coefficient_comparison.to_csv(output_dir / "ridge_top_coefficients.csv", index=False)
training_history_comparison.to_csv(output_dir / "ridge_training_history.csv", index=False)
feature_report.to_csv(output_dir / "ridge_feature_report_no_estimates.csv", index=False)
feature_report_est.to_csv(output_dir / "ridge_feature_report_with_estimates.csv", index=False)

print("Wrote outputs to", output_dir.resolve())

Wrote outputs to /srv/notebooks/[6.0] ML Pricers/Linear_Regression/Ridge_Regression/outputs